name: selftest
on:
  workflow_dispatch:
    inputs:
      controller:
        required: true
        default: 'main'
      jumpstarter:
        required: true
        default: 'main'
      controller_url:
        required: true
        default: 'jumpstarter-dev/jumpstarter-controller'
      jumpstarter_url:
        required: true
        default: 'jumpstarter-dev/jumpstarter'
jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: e2e
      - uses: ./e2e
        with:
          controller-url:  ${{ github.event.inputs.controller_url }}
          jumpstarter-url:  ${{ github.event.inputs.jumpstarter_url }}
          controller-ref:  ${{ github.event.inputs.controller }}
          jumpstarter-ref:  ${{ github.event.inputs.jumpstarter }}
